on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd fre
          yarn
          yarn build
          cd ../
          ls ./src/main/resources/dist/
          node setup.js ${{ secrets.DATABASEURL }} ${{ secrets.DATABASEPWD }}
          cat ./src/main/resources/application.yml
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: |
          java --version
      - name: java package
        run: |
          mvn clean package
          cd target
          ls
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "target"
      - name: Build Image
        env:
          DockerUsername: ${{ secrets.DOCKER_USERNAME }}
          DockerPassword: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DockerUsername -p $DockerPassword
          docker build -t yisar/bcy_api .
          docker push yisar/bcy_api
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: root
          password: ${{ secrets.DEPLOY_PASSWORD }}
          port: 22
          script: |
            docker stop bcy
            docker rm bcy
            docker pull yisar/bcy_api
            docker run -p 8888:8888 -d --name bcy yisar/bcy_api